title: 数据库连接不上了！
date: 2016-06-06 23:04:17
categories: 数据库
tags:
    - MySQL
    - 笔记
---
故事发生在公司的一部内网的测试服务器挂掉后修复后，发布一些python项目之后发现基于有数据库本地连接的基本都跑不起来，全部报错
```
OperationalError: (_mysql_exceptions.OperationalError) (2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)")
```
一开始以为是配置文件写错，但是检查之后发现没什么问题，倒是测试机自己太吊跪，好像只能用unix_socket才能连接，而基于TCP的连接就不行。在ipython试了一下
```python
>>> from torndb import Connection
>>> db = Connection('127.0.0.1', 'mysql', user='root', password='*****')
...
OperationalError: (2003, "Can't connect to MySQL server on '127.0.0.1' (111)")
>>> db = Connection('localhost', 'mysql', user='root', password='*****')
...
OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)")
```
<!--more-->
用localhost连接的倒是可以解决，要么就改my.cnf中socket的路径，或者连接时指定socket路径:
```
db = Connection('/var/run/mysqld/mysqld.sock', 'mysql', user='root', password='*****')
```
或者加一个软链接：
```
ln -s /var/run/mysqld/mysqld.sock /var/lib/mysql/mysql.sock
```
问题解决，可是利用TCP/IP连接这个问题就没那么简单了，不仅如此，发现在console中指定TCP/IP连接也会出问题，
```
mysql -u root -p -h 127.0.0.1
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
```
搜了一些资料，修改了无数次的my.cnf，甚至按照某些回答修改了防火墙:
```
/sbin/iptables -I INPUT -p tcp --dport 3306 -j ACCEPT
```
在mysql user表修改:
```
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
```
然而并没有什么卵用。

最后只能看文档。在MySQL[官方文档](http://dev.mysql.com/doc/refman/5.7/en/can-not-connect-to-server.html)中提到了mysql client连接到mysqld server的两种方式：
* 通过unxi socket文件，通常是/tmp/mysql.sock，优点是比TCP/IP速度快，缺点是客户端只能连接本机的服务端，当指定连接的hostname为localhost时，便是通过unix socket来连接数据库的。
* 通过TCP/IP连接，指定服务器的IP和端口。

同时文档也说明了在连接数据库时可能出现的两种错误及其原因：
>The error (2002) Can't connect to ... normally means that there is no MySQL server running on the system or that you are using an incorrect Unix socket file name or TCP/IP port number when trying to connect to the server. You should also check that the TCP/IP port you are using has not been blocked by a firewall or port blocking service.

针对2002报错，用unix socket的检查是socket file的路径是否正确，使用TCP/IP的检查防火墙或者端口是否有打开，这个检查过了。
>The error (2003) Can't connect to MySQL server on 'server' (10061) indicates that the network connection has been refused. You should check that there is a MySQL server running, that it has network connections enabled, and that the network port you specified is the one configured on the server.

这个叫你检查mysql server是否是在运行，网络连接是否正常（我都能SSH上来），端口设置是否正确之类的。
好像并没有什么帮助，直到：
> Make sure that the server has not been configured to ignore network connections or (if you are attempting to connect remotely) that it has not been configured to listen only locally on its network interfaces.** If the server was started with --skip-networking, it will not accept TCP/IP connections at all. If the server was started with --bind-address=127.0.0.1, it will listen for TCP/IP connections only locally on the loopback interface and will not accept remote connections.**

赶紧看了一下my.cnf，发现果然
```
skip-networking
```
没有注释掉，注释掉重启mysqld，果然问题都解决了。
**果然还是官方文档靠谱!!**

可是有一个问题，在ipython中指明了localhost之后，为什么会用/var/lib/mysql/mysql.sock来连接，而不是在配置文件中的/var/run/mysqld/mysqld.sock呢？
无论是SQLAlchemy还是torndb，都依赖MySQL-python这个依赖包，看了一下出错代码所在的地方
```python
...
class Connection(_mysql.connection):
	...
	autocommit = kwargs2.pop('autocommit', False)
	super(Connection, self).__init__(*args, **kwargs2)
    ...
```
而_mysql是一个.so文件，GitHub上也有[源码](https://github.com/farcepest/MySQLdb1/blob/master/_mysql.c)，发现自己看不懂，回去复习一下C语言。
